# Generated by Django 4.0.2 on 2022-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.ImageField(height_field=501, upload_to='pics', width_field=690)),
                ('login_status', models.CharField(default='Offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=100)),
                ('receiver_username', models.CharField(max_length=100)),
                ('messages', models.TextField()),
                ('msg_date', models.DateTimeField()),
                ('msg_status', models.CharField(default='Unread', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('contents', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
