# Generated by Django 4.0.2 on 2022-02-19 16:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[690, 501], upload_to='pics'),
        ),
    ]
