# Generated by Django 4.0.2 on 2022-02-21 11:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_accounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='msg_status',
            field=models.CharField(default='Unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[690, 501], upload_to='pics'),
        ),
    ]
