# Generated by Django 4.0.2 on 2022-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_accounts_msg_status_alter_accounts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='msg_status',
            field=models.CharField(max_length=20),
        ),
    ]
